[package]
name = "actix-http"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix HTTP primitives"
readme = "README.md"
keywords = ["actix", "http", "framework", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/actix-http/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server",
              "web-programming::websocket"]
license = "MIT OR Apache-2.0"
edition = "2018"

[package.metadata.docs.rs]
features = ["openssl", "rustls", "compress", "secure-cookies", "actors"]

[lib]
name = "actix_http"
path = "src/lib.rs"

[features]
default = []

# openssl
openssl = ["actix-tls/openssl", "actix-connect/openssl"]

# rustls support
rustls = ["actix-tls/rustls", "actix-connect/rustls"]

# enable compressison support
compress = ["flate2", "brotli2"]

# support for secure cookies
secure-cookies = ["cookie/secure"]

# support for actix Actor messages
actors = ["actix"]

[dependencies]
actix-service = "1.0.6"
actix-codec = "0.3.0"
actix-connect = "2.0.0"
actix-utils = "2.0.0"
actix-rt = "1.0.0"
actix-threadpool = "0.3.1"
actix-tls = { version = "2.0.0", optional = true }
actix = { version = "0.10.0", optional = true }

base64 = "0.12"
bitflags = "1.2"
<<<<<<< HEAD
bytes = "0.5.4"
=======
bytes = "0.5.3"
cookie = { version = "0.14.1", features = ["percent-encode"] }
>>>>>>> upstream/master
copyless = "0.1.4"
derive_more = "0.99.5"
either = "1.5.3"
encoding_rs = "0.8"
<<<<<<< HEAD
futures-core = "0.3.4"
futures-util = "0.3.4"
futures-channel = "0.3.4"
=======
futures-channel = { version = "0.3.5", default-features = false }
futures-core = { version = "0.3.5", default-features = false }
futures-util = { version = "0.3.5", default-features = false }
>>>>>>> upstream/master
fxhash = "0.2.1"
h2 = "0.2.4"
http = "0.2.1"
httparse = "1.3"
indexmap = "1.3"
itoa = "0.4"
lazy_static = "1.4"
language-tags = "0.2"
log = "0.4"
mime = "0.3"
percent-encoding = "2.1"
<<<<<<< HEAD
pin-project = "0.4.8"
=======
pin-project = "0.4.17"
>>>>>>> upstream/master
rand = "0.7"
regex = "1.3"
serde = "1.0"
serde_json = "1.0"
sha-1 = "0.9"
slab = "0.4"
serde_urlencoded = "0.6.1"
time = { version = "0.2.9", default-features = false, features = ["std"] }

<<<<<<< HEAD
# for secure cookie
ring = { version = "0.16.12", optional = true }

=======
>>>>>>> upstream/master
# compression
brotli2 = { version="0.3.2", optional = true }
flate2 = { version = "1.0.14", optional = true }

[dev-dependencies]
<<<<<<< HEAD
actix-server = "1.0.2"
actix-connect = { version = "2.0.0-alpha.2", features=["openssl"] }
actix-http-test = { version = "1.0.0", features=["openssl"] }
actix-tls = { version = "2.0.0-alpha.1", features=["openssl"] }
criterion = "0.3"
futures = "0.3.4"
=======
actix-server = "1.0.1"
actix-connect = { version = "2.0.0", features = ["openssl"] }
actix-http-test = { version = "2.0.0", features = ["openssl"] }
actix-tls = { version = "2.0.0", features = ["openssl"] }
criterion = "0.3"
>>>>>>> upstream/master
env_logger = "0.7"
serde_derive = "1.0"
open-ssl = { version="0.10", package = "openssl" }
rust-tls = { version="0.18", package = "rustls" }

[[bench]]
name = "content-length"
harness = false

[[bench]]
name = "status-line"
harness = false

[[bench]]
name = "uninit-headers"
harness = false
