[package]
name = "actix-files"
version = "0.3.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Static files support for actix web."
readme = "README.md"
keywords = ["actix", "http", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/actix-files/"
categories = ["asynchronous", "web-programming::http-server"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
name = "actix_files"
path = "src/lib.rs"

[dependencies]
<<<<<<< HEAD
actix-web = { git = "https://github.com/SaulDoesCode/actix-web", default-features = false }
actix-http = { git = "https://github.com/SaulDoesCode/actix-web" }
actix-service = "1.0.5"
bitflags = "1"
bytes = "0.5.4"
futures = "0.3.4"
derive_more = "0.99.5"
=======
actix-web = { version = "3.0.0", default-features = false }
actix-http = "2.0.0"
actix-service = "1.0.6"
bitflags = "1"
bytes = "0.5.3"
futures-core = { version = "0.3.5", default-features = false }
futures-util = { version = "0.3.5", default-features = false }
derive_more = "0.99.2"
>>>>>>> upstream/master
log = "0.4"
mime = "0.3"
mime_guess = "2.0.3"
percent-encoding = "2.1"
v_htmlescape = "0.10"

[dev-dependencies]
actix-rt = "1.0.0"
<<<<<<< HEAD
actix-web = { git = "https://github.com/SaulDoesCode/actix-web", features=["openssl"] }
=======
actix-web = { version = "3.0.0", features = ["openssl"] }
>>>>>>> upstream/master
